# Generated by Django 4.2.21 on 2025-09-03 11:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('break_duration', models.DurationField(default=datetime.timedelta(0))),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('late', 'Late'), ('on_leave', 'On Leave')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_attendance',
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='staff',
        ),
        migrations.AlterUniqueTogether(
            name='staffshiftassignment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='staffshiftassignment',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='staffshiftassignment',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='staffshiftassignment',
            name='staff',
        ),
        migrations.AlterModelOptions(
            name='advancepayment',
            options={'ordering': ['-request_date']},
        ),
        migrations.RenameField(
            model_name='advancepayment',
            old_name='adjustment_amount_per_day',
            new_name='monthly_deduction',
        ),
        migrations.RenameField(
            model_name='staffprofile',
            old_name='emergency_contact',
            new_name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='advancepayment',
            name='adjustment_start_date',
        ),
        migrations.RemoveField(
            model_name='advancepayment',
            name='advance_date',
        ),
        migrations.RemoveField(
            model_name='advancepayment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='advancepayment',
            name='total_adjusted',
        ),
        migrations.RemoveField(
            model_name='advancepayment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='aadhar_number',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='salary_per_day',
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=datetime.datetime(2025, 9, 3, 11, 59, 6, 896165, tzinfo=datetime.timezone.utc), max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('service', 'Service'), ('housekeeping', 'Housekeeping'), ('management', 'Management'), ('billing', 'Billing')], default=datetime.datetime(2025, 9, 3, 11, 59, 15, 806140, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated'), ('on_leave', 'On Leave')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='full_name',
            field=models.CharField(default=datetime.datetime(2025, 9, 3, 11, 59, 26, 926185, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='hire_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='advancepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='advancepayment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='advancepayment',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='advancepayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='PaymentRecord',
        ),
        migrations.DeleteModel(
            name='StaffShift',
        ),
        migrations.DeleteModel(
            name='StaffShiftAssignment',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='staff.staffprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('staff', 'date')},
        ),
    ]
