# Generated by Django 4.2.7 on 2025-05-10 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='bill',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='final_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='food_items',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='payment_completed',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='room',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='tax_applied',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('room', 'Room')], default='restaurant', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='billitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bills.bill'),
        ),
    ]
