# Generated by Django 4.2.21 on 2025-05-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_bill_room_billitem_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='item',
        ),
        migrations.AddField(
            model_name='bill',
            name='customer_name',
            field=models.CharField(default='Guest', max_length=255),
        ),
        migrations.AddField(
            model_name='bill',
            name='customer_phone',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='bill',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
