# Generated by Django 4.2.21 on 2025-05-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_remove_billitem_item_bill_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
