# Generated by Django 4.2.21 on 2025-05-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_alter_bill_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('online', 'Online')], default='cash', max_length=20),
        ),
    ]
