# Generated by Django 4.2.21 on 2025-06-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_hi',
            field=models.CharField(default='डिफ़ॉल्ट आइटम', max_length=255),
            preserve_default=False,
        ),
    ]
