# Generated by Django 4.2.7 on 2025-10-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='discontinue_reason',
            field=models.TextField(blank=True, help_text='Reason for discontinuation'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='discontinued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Item is available for ordering'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_discontinued',
            field=models.BooleanField(default=False, help_text='Item is permanently discontinued'),
        ),
        migrations.AlterModelTable(
            name='menuitem',
            table='menu_menuitem',
        ),
    ]
