# Generated by Django 4.2.7 on 2025-10-06 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_add_soft_delete_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='discontinue_reason',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='discontinued_at',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_discontinued',
        ),
        migrations.AlterModelTable(
            name='menuitem',
            table=None,
        ),
    ]
