# Generated by Django 4.2.21 on 2025-06-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_description_menuitem_description_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menucategory',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='menucategory',
            name='name_hi',
            field=models.CharField(default='General', max_length=255),
            preserve_default=False,
        ),
    ]
