# Generated by Django 4.2.7 on 2025-09-16 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=18.0, help_text='GST rate in percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='hsn_code',
            field=models.CharField(blank=True, help_text='HSN/SAC code for GST', max_length=20),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_gst_inclusive',
            field=models.BooleanField(default=False, help_text='Is the price GST inclusive?'),
        ),
        migrations.AddField(
            model_name='order',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ordersession',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordersession',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordersession',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bill_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('customer_name', models.CharField(default='Guest', max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=15)),
                ('customer_email', models.CharField(blank=True, max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_charge_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('service_charge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=9.0, max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=9.0, max_digits=5)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_interstate', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('wallet', 'Digital Wallet')], default='cash', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('change_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(default='Hotel Management System', max_length=200)),
                ('business_address', models.TextField(default='Address not set')),
                ('business_gstin', models.CharField(default='GSTIN not set', max_length=15)),
                ('business_phone', models.CharField(default='Phone not set', max_length=15)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_bills_created', to=settings.AUTH_USER_MODEL)),
                ('orders', models.ManyToManyField(related_name='restaurant_bills', to='restaurant.order')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_bills', to='restaurant.table')),
            ],
            options={
                'db_table': 'restaurant_bill',
                'ordering': ['-created_at'],
            },
        ),
    ]
