# Generated by Django 4.2.7 on 2025-09-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menuitem_gst_rate_menuitem_hsn_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='gst_rate',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='hsn_code',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_gst_inclusive',
        ),
        migrations.RemoveField(
            model_name='order',
            name='base_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='gst_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='gst_rate',
        ),
        migrations.RemoveField(
            model_name='ordersession',
            name='gst_amount',
        ),
        migrations.RemoveField(
            model_name='ordersession',
            name='service_charge',
        ),
        migrations.RemoveField(
            model_name='ordersession',
            name='subtotal',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
