# Generated by Django 4.2.7 on 2025-09-17 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0003_remove_menuitem_gst_rate_remove_menuitem_hsn_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineOrderBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_data', models.JSONField(help_text='Complete order data')),
                ('table_number', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'offline_order_backup',
                'ordering': ['created_at'],
            },
        ),
        migrations.RenameField(
            model_name='ordersession',
            old_name='total_amount',
            new_name='service_charge',
        ),
        migrations.AddField(
            model_name='kitchendisplaysettings',
            name='auto_confirm_orders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kitchendisplaysettings',
            name='group_orders_by_table',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kitchendisplaysettings',
            name='notification_sound_volume',
            field=models.DecimalField(decimal_places=2, default=0.8, max_digits=3),
        ),
        migrations.AddField(
            model_name='kitchendisplaysettings',
            name='offline_mode_enabled',
            field=models.BooleanField(default=True, help_text='Store orders when offline'),
        ),
        migrations.AddField(
            model_name='order',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes for this order'),
        ),
        migrations.AddField(
            model_name='order',
            name='backup_data',
            field=models.JSONField(default=dict, help_text='Backup data for offline orders'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_kds_notified',
            field=models.BooleanField(default=False, help_text='Whether KDS was notified'),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('dine_in', 'Dine In'), ('mobile', 'Mobile Order'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery')], default='dine_in', max_length=20),
        ),
        migrations.AddField(
            model_name='ordersession',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes for billing'),
        ),
        migrations.AddField(
            model_name='ordersession',
            name='billed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_billed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordersession',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ordersession',
            name='payment_details',
            field=models.JSONField(default=dict, help_text='Payment breakdown for mixed payments'),
        ),
        migrations.AddField(
            model_name='ordersession',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('online', 'Online'), ('mixed', 'Mixed Payment')], max_length=20),
        ),
        migrations.AddField(
            model_name='ordersession',
            name='printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordersession',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ordersession',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='table',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='table',
            name='notes',
            field=models.TextField(blank=True, help_text='Admin notes about the table'),
        ),
        migrations.AddField(
            model_name='table',
            name='priority_level',
            field=models.IntegerField(default=1, help_text='1=Normal, 2=VIP, 3=Premium'),
        ),
        migrations.AddField(
            model_name='table',
            name='qr_code_url',
            field=models.URLField(blank=True, help_text='QR code for mobile ordering'),
        ),
        migrations.AlterField(
            model_name='ordersession',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
