# Generated by Django 4.2.7 on 2025-09-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_offlineorderbackup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersession',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
