# Generated by Django 4.2.7 on 2025-09-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_ordersession_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ordersession',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
