# Generated by Django 4.2.7 on 2025-09-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_order_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersession',
            name='apply_gst',
            field=models.BooleanField(default=True, help_text='Whether to apply GST to this session'),
        ),
    ]
