# Generated by Django 4.2.7 on 2025-10-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_menucategory_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategory',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='description_hi',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='name_hi',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='description_hi',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='name_hi',
        ),
    ]
