# Generated by Django 4.2.7 on 2025-10-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_remove_menucategory_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='name_en',
            field=models.CharField(blank=True, help_text='English name for compatibility', max_length=255),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='name_hi',
            field=models.CharField(blank=True, help_text='Hindi name for compatibility', max_length=255),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='available',
            field=models.BooleanField(default=True, help_text='Backward compatibility field'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_en',
            field=models.TextField(blank=True, help_text='English description for compatibility'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_hi',
            field=models.TextField(blank=True, help_text='Hindi description for compatibility'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_en',
            field=models.CharField(blank=True, help_text='English name for compatibility', max_length=255),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_hi',
            field=models.CharField(blank=True, help_text='Hindi name for compatibility', max_length=255),
        ),
    ]
