# Generated by Django 4.2.7 on 2025-10-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_enhance_inventory_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycategory',
            name='description_en',
            field=models.TextField(blank=True, help_text='English description'),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='description_hi',
            field=models.TextField(blank=True, help_text='Hindi description'),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='name_en',
            field=models.CharField(blank=True, help_text='English name', max_length=100),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='name_hi',
            field=models.CharField(blank=True, help_text='Hindi name', max_length=100),
        ),
    ]
