# Generated by Django 4.2.7 on 2025-09-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0002_add_payment_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='include_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlypayment',
            name='paid_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlypayment',
            name='present_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlypayment',
            name='working_days',
            field=models.IntegerField(default=30),
        ),
    ]
