# Generated by Django 4.2.7 on 2025-10-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0003_alter_attendance_include_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='description_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='name_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='designation',
            name='name_hi',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
