# Generated by Django 4.2.21 on 2025-06-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_delete_roomservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='type',
            new_name='type_en',
        ),
        migrations.AddField(
            model_name='room',
            name='description_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='type_hi',
            field=models.CharField(default='सामान्य कमरा', max_length=100),
            preserve_default=False,
        ),
    ]
