# Generated by Django 4.2.7 on 2025-09-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roombooking_bookingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='aadhaar_card',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='check_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='check_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
